from collections.abc import Mapping, Sequence
from typing import Protocol

from app.modules.identity.domain.contracts import ExternalIdentity, ProvisionedUser


class IdentityTokenVerifierPort(Protocol):
    def verify(self, token: str) -> ExternalIdentity: ...


class IdentityProvisioningPort(Protocol):
    def provision_tenant_admin(self, *, email: str, name: str) -> ProvisionedUser: ...
    def delete_user(self, user_id: str) -> None: ...
    def send_verification_email(self, user_id: str) -> bool: ...
    def trigger_password_reset_email(self, *, email: str) -> bool: ...
    def create_password_change_ticket(self, *, email: str) -> str | None: ...


class BillingOnboardingPort(Protocol):
    def create_default_plan(self, tenant_id: str, plan: object | None) -> None: ...
    def tenant_usage_snapshot(self, tenant_id: str) -> Mapping[str, object]: ...
    def cleanup_tenant(self, tenant_id: str) -> Mapping[str, int]: ...


class LegacyAgentAdministrationPort(Protocol):
    def create_agents(self, tenant_id: str, agents: Sequence[Mapping[str, object]]) -> Sequence[object]: ...
    def list_agents(self, tenant_id: str) -> Sequence[object]: ...
    def cleanup_tenant(self, tenant_id: str) -> int: ...


class TenantDependentCleanupPort(Protocol):
    def cleanup_tenant(self, tenant_id: str) -> Mapping[str, int]: ...
