from datetime import datetime
from decimal import Decimal
from typing import Protocol


class UsageMeterPort(Protocol):
    def billed_minutes(self, tenant_id: str, period_start: datetime, period_end: datetime) -> Decimal: ...


class TenantAccountPort(Protocol):
    def get(self, tenant_id: str): ...
    def get_by_slug(self, slug: str): ...
    def list_tenants(self): ...
    def set_usage_suspension(self, tenant_id: str, suspended: bool, *, commit: bool) -> None: ...
